// utils/config.plans.js
const BASE_CHANNELS = ["web", "instagram", "facebook", "whatsapp"];
const getChannels = (channels) => [...BASE_CHANNELS, ...channels];

export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    description: "Basic chatbot functionality for small projects",
    prices: { monthly: 0, yearly: 0 },
    limits: {
      chatbots: 1,
      messages: 300,
      members: 1,
      storage: 1, // GB
      conversations: 100,
      integrations: 1,
      automationRules: 0,
      dripCampaigns: 0,
      landingPages: 1,
      adCampaigns: 0,
      teamRoles: 0,
      aiModelTraining: 0,
      apiCalls: 1000,
      adCredits: 0,
    },
    features: {
      chatbotAutomation: {
        channels: getChannels([]),
        visualFlowBuilder: false,
        multilingualSupport: 1,
        templates: false,
        fileAttachments: false,
        customFlows: false,
      },
      adsAutomation: {
        enabled: false,
        adCopyGeneration: false,
        targeting: false,
        budgetManagement: false,
        autoPublishing: false,
        audienceSegmentation: false,
        credits: 0,
      },
      seoTools: {
        enabled: false,
        keywordResearch: false,
        longTailKeywords: false,
        dailyUpdates: false,
      },
      landingBuilder: {
        enabled: true,
        dragDropEditor: false,
        templates: false,
        formBuilders: false,
        popups: false,
      },
      crmAndDripCampaigns: {
        enabled: false,
        leadScoring: false,
        visitorTracking: false,
        crmSync: false,
        emailSequences: false,
        behavioralTriggers: false,
        abTesting: false,
      },
      aiAgent: {
        responseTuning: false,
        modelTraining: false,
        customModels: false,
      },
      growthFeatures: {
        analyticsDashboard: false,
        customBranding: false,
        teamCollaboration: false,
        dynamicContent: false,
        webinarIntegration: false,
        membershipSites: false,
        paymentGateways: false,
      },
      enterpriseFeatures: {
        prioritySupport: false,
        whiteLabel: false,
        apiAccess: false,
        webhooks: false,
        sso: false,
        dedicatedInstance: false,
        sla99_9: false,
        customDataCenter: false,
        auditLogs: false,
        dataResidency: false,
        hipaaCompliance: false,
        accountManager: false,
      },
    },
    metadata: {
      recommended: false,
      popular: false,
      trialDays: 0,
    },
  },
  starter: {
    id: "starter",
    name: "Starter",
    description: "Ideal for solopreneurs & SaaS founders getting started",
    prices: { monthly: 999, yearly: 9999 },
    limits: {
      chatbots: 2,
      messages: 3000,
      members: 2,
      storage: 5,
      conversations: 1000,
      integrations: 2,
      automationRules: 3,
      dripCampaigns: 2,
      landingPages: 3,
      adCampaigns: 1,
      teamRoles: 0,
      aiModelTraining: 0,
      apiCalls: 10000,
      adCredits: 0,
    },
    features: {
      chatbotAutomation: {
        channels: getChannels(["telegram"]),
        visualFlowBuilder: true,
        multilingualSupport: 2,
        templates: true,
        fileAttachments: true,
        customFlows: true,
      },
      adsAutomation: {
        enabled: true,
        adCopyGeneration: true,
        targeting: false,
        budgetManagement: false,
        autoPublishing: false,
        audienceSegmentation: false,
        credits: 0,
      },
      seoTools: {
        enabled: true,
        keywordResearch: true,
        longTailKeywords: true,
        dailyUpdates: false,
      },
      landingBuilder: {
        enabled: true,
        dragDropEditor: true,
        templates: true,
        formBuilders: true,
        popups: false,
      },
      crmAndDripCampaigns: {
        enabled: true,
        leadScoring: true,
        visitorTracking: true,
        crmSync: true,
        emailSequences: true,
        behavioralTriggers: false,
        abTesting: false,
      },
      aiAgent: {
        responseTuning: true,
        modelTraining: false,
        customModels: false,
      },
      growthFeatures: {
        analyticsDashboard: true,
        customBranding: true,
        teamCollaboration: false,
        dynamicContent: false,
        webinarIntegration: false,
        membershipSites: false,
        paymentGateways: false,
      },
      enterpriseFeatures: {
        prioritySupport: false,
        whiteLabel: false,
        apiAccess: true,
        webhooks: true,
        sso: false,
        dedicatedInstance: false,
        sla99_9: false,
        customDataCenter: false,
        auditLogs: false,
        dataResidency: false,
        hipaaCompliance: false,
        accountManager: false,
      },
    },
    metadata: {
      recommended: false,
      popular: false,
      trialDays: 3,
    },
  },
  pro: {
    id: "pro",
    name: "Pro",
    description: "Advanced features for growing businesses with AI-powered ads",
    prices: { monthly: 2499, yearly: 23999 },
    limits: {
      chatbots: 5,
      messages: 10000,
      members: 10,
      storage: 50,
      conversations: 5000,
      integrations: 5,
      automationRules: 10,
      dripCampaigns: 5,
      landingPages: 10,
      adCampaigns: 3,
      teamRoles: 0,
      aiModelTraining: 0,
      apiCalls: 50000,
      adCredits: 500,
    },
    features: {
      chatbotAutomation: {
        channels: getChannels(["telegram", "sms", "discord"]),
        visualFlowBuilder: true,
        multilingualSupport: 5,
        templates: true,
        fileAttachments: true,
        customFlows: true,
      },
      adsAutomation: {
        enabled: true,
        adCopyGeneration: true,
        targeting: true,
        budgetManagement: true,
        autoPublishing: true,
        audienceSegmentation: true,
        credits: 500,
      },
      seoTools: {
        enabled: true,
        keywordResearch: true,
        longTailKeywords: true,
        dailyUpdates: true,
      },
      landingBuilder: {
        enabled: true,
        dragDropEditor: true,
        templates: true,
        formBuilders: true,
        popups: true,
      },
      crmAndDripCampaigns: {
        enabled: true,
        leadScoring: true,
        visitorTracking: true,
        crmSync: true,
        emailSequences: true,
        behavioralTriggers: true,
        abTesting: true,
      },
      aiAgent: {
        responseTuning: true,
        modelTraining: false,
        customModels: false,
      },
      growthFeatures: {
        analyticsDashboard: true,
        customBranding: true,
        teamCollaboration: false,
        dynamicContent: false,
        webinarIntegration: false,
        membershipSites: false,
        paymentGateways: false,
      },
      enterpriseFeatures: {
        prioritySupport: true,
        whiteLabel: false,
        apiAccess: true,
        webhooks: true,
        sso: false,
        dedicatedInstance: false,
        sla99_9: false,
        customDataCenter: false,
        auditLogs: false,
        dataResidency: false,
        hipaaCompliance: false,
        accountManager: false,
      },
    },
    metadata: {
      recommended: false,
      popular: true,
      trialDays: 5,
    },
  },
  growth: {
    id: "growth",
    name: "Growth",
    description:
      "For scaling businesses with advanced automation & team collaboration",
    prices: { monthly: 4999, yearly: 47999 },
    limits: {
      chatbots: 15,
      messages: 50000,
      members: 30,
      storage: 250,
      conversations: 25000,
      integrations: 15,
      automationRules: 30,
      dripCampaigns: 20,
      landingPages: 50,
      adCampaigns: 15,
      teamRoles: 5,
      aiModelTraining: 3,
      apiCalls: 100000,
      adCredits: 2500,
    },
    features: {
      chatbotAutomation: {
        channels: getChannels(["slack", "voice", "telegram", "sms", "discord"]),
        visualFlowBuilder: true,
        multilingualSupport: 15,
        templates: true,
        fileAttachments: true,
        customFlows: true,
      },
      adsAutomation: {
        enabled: true,
        adCopyGeneration: true,
        targeting: true,
        budgetManagement: true,
        autoPublishing: true,
        audienceSegmentation: true,
        credits: 2500,
      },
      seoTools: {
        enabled: true,
        keywordResearch: true,
        longTailKeywords: true,
        dailyUpdates: true,
      },
      landingBuilder: {
        enabled: true,
        dragDropEditor: true,
        templates: true,
        formBuilders: true,
        popups: true,
      },
      crmAndDripCampaigns: {
        enabled: true,
        leadScoring: true,
        visitorTracking: true,
        crmSync: true,
        emailSequences: true,
        behavioralTriggers: true,
        abTesting: true,
      },
      aiAgent: {
        responseTuning: true,
        modelTraining: true,
        customModels: true,
      },
      growthFeatures: {
        analyticsDashboard: true,
        customBranding: true,
        teamCollaboration: true,
        dynamicContent: true,
        webinarIntegration: true,
        membershipSites: true,
        paymentGateways: true,
      },
      enterpriseFeatures: {
        prioritySupport: true,
        whiteLabel: true,
        apiAccess: true,
        webhooks: true,
        sso: true,
        dedicatedInstance: false,
        sla99_9: false,
        customDataCenter: false,
        auditLogs: false,
        dataResidency: false,
        hipaaCompliance: false,
        accountManager: false,
      },
    },
    metadata: {
      recommended: true,
      popular: false,
      trialDays: 7,
    },
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    description:
      "For large organizations needing enterprise-grade security & reliability",
    prices: { monthly: 19999, yearly: 199999 },
    limits: {
      chatbots: "Infinity",
      messages: "Infinity",
      members: "Infinity",
      storage: "Infinity",
      conversations: "Infinity",
      integrations: "Infinity",
      automationRules: "Infinity",
      dripCampaigns: "Infinity",
      landingPages: "Infinity",
      adCampaigns: "Infinity",
      teamRoles: "Infinity",
      aiModelTraining: "Infinity",
      apiCalls: 1000000,
      adCredits: "Infinity",
      dedicatedConcurrency: 20,
    },
    features: {
      chatbotAutomation: {
        channels: getChannels([
          "slack",
          "voice",
          "telegram",
          "sms",
          "discord",
          "customSDK",
        ]),
        visualFlowBuilder: true,
        multilingualSupport: "Infinity",
        templates: true,
        fileAttachments: true,
        customFlows: true,
      },
      adsAutomation: {
        enabled: true,
        adCopyGeneration: true,
        targeting: true,
        budgetManagement: true,
        autoPublishing: true,
        audienceSegmentation: true,
        credits: "Infinity",
      },
      seoTools: {
        enabled: true,
        keywordResearch: true,
        longTailKeywords: true,
        dailyUpdates: true,
      },
      landingBuilder: {
        enabled: true,
        dragDropEditor: true,
        templates: true,
        formBuilders: true,
        popups: true,
      },
      crmAndDripCampaigns: {
        enabled: true,
        leadScoring: true,
        visitorTracking: true,
        crmSync: true,
        emailSequences: true,
        behavioralTriggers: true,
        abTesting: true,
      },
      aiAgent: {
        responseTuning: true,
        modelTraining: true,
        customModels: true,
      },
      growthFeatures: {
        analyticsDashboard: true,
        customBranding: true,
        teamCollaboration: true,
        dynamicContent: true,
        webinarIntegration: true,
        membershipSites: true,
        paymentGateways: true,
      },
      enterpriseFeatures: {
        prioritySupport: true,
        whiteLabel: true,
        apiAccess: true,
        webhooks: true,
        sso: true,
        dedicatedInstance: true,
        sla99_9: true,
        customDataCenter: true,
        auditLogs: true,
        dataResidency: true,
        hipaaCompliance: true,
        accountManager: true,
        developerSupport: true,
        trainingSessions: true,
      },
    },
    metadata: {
      recommended: false,
      popular: false,
      trialDays: 14,
      implementationSupport: true,
    },
  },
};
