services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - /app/node_modules # prevent overwriting node_modules
    command: npm run dev
