services:
  nextjs:
    build:
      context: .
      target: production # Change to 'production' for prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
