import {
  AnalyticsIcon,
  BotIcon,
  ChatBotAI,
  ContactsIcon,
  ConversationsIcon,
  CreativeIcon,
  DashboardIcon,
  HelpIcon,
  SettingsIcon,
  TemplatesIcon,
} from "@/public/Images/svg_ecod";
import {
  ArrowPathIcon,
  ClipboardDocumentIcon,
} from "@heroicons/react/24/outline";
import {
  Bell,
  ChartBar,
  Cpu,
  GlobeIcon,
  Key,
  Megaphone,
  PaintBucket,
  Plug,
  Puzzle,
  Target,
} from "lucide-react";
import {
  FiBook,
  FiCreditCard,
  FiLifeBuoy,
  FiLock,
  FiUser,
  FiUsers,
} from "react-icons/fi";

export const Icons = {
  bot: <BotIcon className="w-4 h-4 text-current" />,
  analytics: <AnalyticsIcon className="w-4 h-4 text-current" />,
  chatbot: <ChatBotAI className="w-4 h-4 text-current" />,
  dashboard: <DashboardIcon className="w-4 h-4 text-current" />,
  conversation: <ConversationsIcon className="w-4 h-4 text-current" />,
  contacts: <ContactsIcon className="w-4 h-4 text-current" />,
  megaphone: <Megaphone className="w-4 h-4 text-current" />,
  ads_creative: <CreativeIcon className="w-4 h-4 text-current" />,
  templates: <TemplatesIcon className="w-4 h-4 text-current" />,
  settings: <SettingsIcon className="w-4 h-4 text-current" />,
  help: <HelpIcon className="w-4 h-4 text-current" />,
  target: <Target className="w-4 h-4 text-current" />,
  billing: <FiCreditCard className="w-4 h-4 text-current" />,
  user: <FiUser className="w-4 h-4 text-current" />,
  lock: <FiLock className="w-4 h-4 text-current" />,
  bell: <Bell className="w-4 h-4 text-current" />,
  users: <FiUsers className="w-4 h-4 text-current" />,
  key: <Key className="w-4 h-4 text-current" />,
  chart: <ChartBar className="w-4 h-4 text-current" />,
  puzzle: <Puzzle className="w-4 h-4 text-current" />,
  arrow_path: <ArrowPathIcon className="w-4 h-4 text-current" />,
  globe: <GlobeIcon className="w-4 h-4 text-current" />,
  clip_doc: <ClipboardDocumentIcon className="w-4 h-4 text-current" />,
  cpu: <Cpu className="w-4 h-4 text-current" />,
  paint: <PaintBucket className="w-4 h-4 text-current" />,
  plug: <Plug className="w-4 h-4 text-current" />,
  lifebuoy: <FiLifeBuoy className="w-4 h-4 text-current" />,
  book: <FiBook className="w-4 h-4 text-current" />,
};
