const fontFamilies = [
  // ✅ System & Web-Safe Fonts
  { name: "Default (System)", value: "system-ui" },
  { name: "Arial", value: "Arial, sans-serif" },
  { name: "Verdana", value: "Verdana, sans-serif" },
  { name: "Helvetica", value: "Helvetica, sans-serif" },
  { name: "Tahoma", value: "Tahoma, sans-serif" },
  { name: "Trebuchet MS", value: "'Trebuchet MS', sans-serif" },
  { name: "Times New Roman", value: "'Times New Roman', serif" },
  { name: "Georgia", value: "Georgia, serif" },
  { name: "Garamond", value: "'Garamond', serif" },
  { name: "Courier New", value: "'Courier New', monospace" },
  { name: "Lucida Console", value: "'Lucida Console', monospace" },

  // ✅ Popular Google Fonts
  { name: "Roboto", value: "'Roboto', sans-serif" },
  { name: "Open Sans", value: "'Open Sans', sans-serif" },
  { name: "Lato", value: "'Lato', sans-serif" },
  { name: "Montserrat", value: "'Montserrat', sans-serif" },
  { name: "Poppins", value: "'Poppins', sans-serif" },
  { name: "Nunito", value: "'Nunito', sans-serif" },
  { name: "Raleway", value: "'Raleway', sans-serif" },
  { name: "Oswald", value: "'Oswald', sans-serif" },
  { name: "Merriweather", value: "'Merriweather', serif" },
  { name: "Playfair Display", value: "'Playfair Display', serif" },
  { name: "Ubuntu", value: "'Ubuntu', sans-serif" },
  { name: "Inter", value: "'Inter', sans-serif" },
  { name: "PT Sans", value: "'PT Sans', sans-serif" },
  { name: "Fira Sans", value: "'Fira Sans', sans-serif" },
  { name: "Work Sans", value: "'Work Sans', sans-serif" },
  { name: "Dancing Script", value: "'Dancing Script', cursive" },
  { name: "Bebas Neue", value: "'Bebas Neue', cursive" },
  { name: "Comfortaa", value: "'Comfortaa', sans-serif" },
  { name: "Caveat", value: "'Caveat', cursive" },
  { name: "Pacifico", value: "'Pacifico', cursive" },
  { name: "Anton", value: "'Anton', sans-serif" },
  { name: "Lobster", value: "'Lobster', cursive" },
  { name: "Barlow", value: "'Barlow', sans-serif" },
  { name: "Rubik", value: "'Rubik', sans-serif" },
  { name: "Teko", value: "'Teko', sans-serif" },
  { name: "Josefin Sans", value: "'Josefin Sans', sans-serif" },
  { name: "Quicksand", value: "'Quicksand', sans-serif" },
  { name: "Cinzel", value: "'Cinzel', serif" },
  { name: "Karla", value: "'Karla', sans-serif" },
  { name: "Zilla Slab", value: "'Zilla Slab', serif" },
  { name: "Bitter", value: "'Bitter', serif" },
  { name: "IBM Plex Sans", value: "'IBM Plex Sans', sans-serif" },
  { name: "IBM Plex Serif", value: "'IBM Plex Serif', serif" },
  { name: "IBM Plex Mono", value: "'IBM Plex Mono', monospace" },
  { name: "Source Sans Pro", value: "'Source Sans Pro', sans-serif" },
  { name: "Source Serif Pro", value: "'Source Serif Pro', serif" },
  { name: "Source Code Pro", value: "'Source Code Pro', monospace" },
  { name: "Exo", value: "'Exo', sans-serif" },
  { name: "DM Sans", value: "'DM Sans', sans-serif" },
  { name: "DM Serif Display", value: "'DM Serif Display', serif" },
  { name: "Amatic SC", value: "'Amatic SC', cursive" },
  { name: "Special Elite", value: "'Special Elite', cursive" },
  { name: "Press Start 2P", value: "'Press Start 2P', cursive" },
];

export default fontFamilies;
