services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - MONGODB_URI=mongodb+srv://ecodservice:Reddy143@blog.bp2ex.mongodb.net/auto-bot?retryWrites=true&w=majority
    command: sh -c "rm -rf .next && npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
