services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb?replicaSet=rs0
      - NODE_ENV=development

volumes:
  mongo-data:
